feat: transition to user dashboards post login
ArthurAtangana/club-management-system pull request #20
Opened 2024-03-28 23:14 UTC by BraedenKloke

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] ✅ Test
- [ ] 🧑‍💻 Refactor

## Description
After authenticating a user, system gets the user's group then loads the appropriate dashboard.
Command names are taken from the use case diagrams.

## How to test
* Run the CLI and enter John Smith's credentials to go the admin view (see screenshot).
* Run the CLI and enter Jane Doe's credentials to go to the trainer's view
* Run the CLI and enter Tom Black's credentials to go to the trainer's view

## Added/updated tests?

- [ ] Yes
- [X] No, and this is why: No new interactions with DB.
- [ ] I need help with writing tests:.

## Screenshots
<img width="864" alt="image" src="https://github.com/ArthurAtangana/club-management-system/assets/77079888/650b5179-0ad9-4eed-95f3-cfd9b2edd0ad">

2024-03-29 00:49 UTC, ArthurAtangana approved these changes

2024-04-01 13:41 UTC, Rebecca-Elliott requested changes
convert your YUCK! Big IF block ... to use a switch statement, would be cleaner. Or have an abstract command class and each command is a a sub class that implements its own version of handleCommand().
If you don't want to change it though it is fine.

2024-04-01 13:41 UTC, Rebecca-Elliott commented on src/main/java/ui/ClubManagementCLI.java
> +        // YUCK! Big IF block ...
use switch statement for all the else if blocks

2024-04-01 14:29 UTC, Rebecca-Elliott approved these changes

2024-04-01 19:27 UTC, merged